### ISSUE TITLE
Sankey Chart is hard coded to use TWh as a unit in tool tops

### ISSUE THREAD

**Issue by JohnOmernik** [d3blocks/d3blocks#10]
Probably from this line: 

https://github.com/d3blocks/d3blocks/blob/53169b5605908d82982e2e133e76ddfa0ec28117/d3blocks/sankey/d3js/sankey.html.j2#L64

Having a variable for units (or None) would be preferred.

**Comment by erdogant** [comment]
I removed the string `TWh`.  The update will be visible in release v1.2.8.

**Comment by erdogant** [comment]
Dix is available in latest version.
`pip install -U d3blocks `
