### ISSUE TITLE
New Issue: Moving Bubble Time Control

### ISSUE THREAD

**Issue by JohnOmernik** [d3blocks/d3blocks#12]
Could ticks be controlled? I.e. I believe Slow Medium and Fast define how many ticks happen per second, what if we could use larger time windows say "day" and be able to advance or rewind manually? Help tell a story at the speed of the story tellr?

**Comment by erdogant** [comment]
Yes this should be possible now with the parameter `timedelta`.
You can specify `seconds`, `minutes `and `days`.

**Comment by erdogant** [comment]
closing this one.
