### ISSUE TITLE
Idea: Moving Bubble Bubble Size

### ISSUE THREAD

**Issue by JohnOmernik** [d3blocks/d3blocks#13]
What if you wanted to represent something in the bubble being a certain amount of something. Say KWhs... you  when it was moving from one point to another, it would be cool to show 10 KWh as a tightly bound group of 10 moving together. Maybe it could be joined to a larger circle, but we may lose the ability to discern the meaning of the size other than "bigger".  Just tossing ideas out here....

**Comment by beldaz** [comment]
+100 It would be great if a size column could be including in the dataframe, and the sample size is updated at that time accordingly.

**Comment by erdogant** [comment]
This feature is meanwhile added into this chart!
See [here](https://d3blocks.github.io/d3blocks/pages/html/MovingBubbles.html) for the documentation
