### ISSUE TITLE
Moving Bubbles: Control of colors

### ISSUE THREAD

**Issue by JohnOmernik** [d3blocks/d3blocks#14]
Would it be possible to color based on a the item moving, and allow the colors to stay original no matter where they move?  That could be helpful to show clusters of different groups at different times.

**Comment by erdogant** [comment]
I added the possibility to specify colors and sizes per node! 
You can do this now by creating a dictionary where you need to specify the size and color for the sample_id.
See example:

```

# Load d3blocks
from d3blocks import D3Blocks
#
# Initialize
d3 = D3Blocks(chart='movingbubbles')
#
# Import example
df = d3.import_example('random_time', n=1000, c=100, date_start="1-1-2000 00:10:05", date_stop="1-1-2000 23:59:59")
#
# Specify the colors and node sizes for the specific sample_id
size = {1: 20, 3: 40}
color = {1: '#FF0000', 3: '#000FFF'}
#
# Show
d3.movingbubbles(df, color=color, size=size)
```

**Comment by erdogant** [comment]
Closing this one
