### ISSUE TITLE
Circular import error

### ISSUE THREAD

**Issue by mfleuren** [d3blocks/d3blocks#2]
Hi,

I've tried downloading your package following the instructions on the docs pages, using a clean Anaconda env and python 3.10, but I get circular import errors when importing the package in Python. 

from d3blocks import D3Blocks
ImportError: cannot import name 'D3Blocks' from partially initialized module 'd3blocks' (most likely due to a circular import) 

I tried multiple versions of the code (1.0.7, 1.0.6, 1.0.2) without success.

Any clues how to fix this?

Best regards,
Mike

**Comment by erdogant** [comment]
Not sure why this happens. I can not replicate the error. Does the error message also point to a certain line?

**Comment by mfleuren** [comment]
I tried to replicate this on a separate system on both Python 3.9 and 3.10 and cannot replicate the issue either. So I'll just close the issue and try again on the former system later.

**Comment by erdogant** [comment]
👍🏻

**Comment by baiwfg2** [comment]
I met with this error too, on windows 10, python3.11.3. I do same on linux, but it's ok.
```
>>> import d3blocks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\workspace\code-examples\python\plotter\d3blocks.py", line 2, in <module>
    from d3blocks import D3Blocks
ImportError: cannot import name 'D3Blocks' from partially initialized module 'd3blocks' (most likely due to a circular import) (E:\workspace\code-examples\python\plotter\d3blocks.py)
>>> from d3blocks import D3Blocks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\workspace\code-examples\python\plotter\d3blocks.py", line 2, in <module>
    from d3blocks import D3Blocks
ImportError: cannot import name 'D3Blocks' from partially initialized module 'd3blocks' (most likely due to a circular import) (E:\workspace\code-examples\python\plotter\d3blocks.py)
```

**Comment by oliver3** [comment]
Thanks for letting us know your solution!
