### ISSUE TITLE
Library Import problem : ModuleNotFoundError: No module named 'movingbubbles'

### ISSUE THREAD

**Issue by MohamedTaha314** [d3blocks/d3blocks#20]
After installing d3blocks via Pypi in Anaconda prompt, using: pip install -U d3blocks
Importing the library in Jupyter Notebook is impossible, as shown in the image below, I am on Python 3.9.12.
![image](https://user-images.githubusercontent.com/57417172/213154863-85c06f75-68fe-401b-9cc5-b16cd5c61891.png)

Searched for a solution or similar cases on the Internet, but I did not find any, maybe it is a very recent issue.

**Comment by erdogant** [comment]
oops. some import fixes.

update to the latest version with:
`pip install -U d3blocks
`

**Comment by MohamedTaha314** [comment]
Thank you, keep up the good work !
