### ISSUE TITLE
No module named 'd3blocks.matrix.Matrix'

### ISSUE THREAD

**Issue by fedequaranta** [d3blocks/d3blocks#21]
Hi,

I can't import d3blocks into my jupyter notebook. It gives me this error with the latest version 1.2.5:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/123079031/213466211-805ccacd-85fb-48b7-87fd-d1e4892c47f2.png">

Could you help me?

**Comment by erdogant** [comment]
thanks for mentioning this. I did forget the init file and therefore the file was nog within the repo. It is fixed now!
update with: `pip install -U d3blocks` The version should be >= v1.2.6

**Comment by fedequaranta** [comment]
Thank you for the fast fix. I have a last question about reset of the states when the journey ends: for example, if I consider only one day with timedelta = 'minutes', at the end of the day the last state occurred for example at 23:50 does not change while the clock starts again from 00:00. Is there any way to repeat the same journey?

**Comment by erdogant** [comment]
True. That would be better. I need to look into this.

**Comment by erdogant** [comment]
I created a small fix that the process start all over when it comes to the end. However, there are many ways to start the "repeat" functionality. I just let it continue to after the last step is finished.
