### ISSUE TITLE
No capability to change tick labels

### ISSUE THREAD

**Issue by eafpres** [d3blocks/d3blocks#26]
```
d3.violin(x = ground_truth.company,
          y = ground_truth.cost,
          color = colors,
          tooltip = list(ground_truth.cost),
          ylim = ylim,
          bins = 20,
          figsize = (1000, 1000),
          showfig = True)
```
produces expected output, but the tick labels are very small; there appears to be no way to change either the text properties or the y-axis tick locations.

**Comment by erdogant** [comment]
I added the functionality!
Update to the latest version with: `pip install -U d3blocks`
More information and examples can be found [here](https://d3blocks.github.io/d3blocks/pages/html/Violin.html).

<a href='https://www.buymeacoffee.com/erdogant' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://cdn.ko-fi.com/cdn/kofi1.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>

**Comment by eafpres** [comment]
Thanks for this. However, it appears this var is for the tooltip fontsize.  I'll create an issue and show code and outputs.
