### ISSUE TITLE
Adding Labels to D3graph links

### ISSUE THREAD

**Issue by daan-ds** [d3blocks/d3blocks#27]
Great project, really useful work!

Would it be possible to add the functionality of adding labels to the links/edges in the D3graphs? ([edge properties](https://erdogant.github.io/d3graph/pages/html/Core_Functionalities.html#edge-properties))

An example of such a graph is found [here](https://observablehq.com/@xianwu/force-directed-graph-network-graph-with-arrowheads-and-lab).

This would be really helpful!

**Comment by erdogant** [comment]
Interesting. I am going to look into it.

**Comment by daan-ds** [comment]
Hi Erdogan,

Did you already have some time to look into this? It would be greatly appreciated!

**Comment by erdogant** [comment]
I took the time today to implement this functionality.
If you force update `d3graph`, then it will also automatically work in `d3blocks`.

`pip install -U d3graph
`

Details can be found [here](https://erdogant.github.io/d3graph/pages/html/Edge%20properties.html#edge-labels).

You can always thank me with a coffee :)
<a href='https://www.buymeacoffee.com/erdogant' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://cdn.ko-fi.com/cdn/kofi1.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>
