### ISSUE TITLE
Selecting colors for chord diagrams

### ISSUE THREAD

**Issue by jmpion** [d3blocks/d3blocks#3]
Hi, when using the chord diagram on some data, I wanted to select the colors of the diagrams by myself, but it turns out I couldn't find a way to change the colormap.
It would be a great addition to the library, if it were possible to **select the colors for chord diagrams**.
In the meantime, thanks for this amazing library and keep up the great work!

**Comment by erdogant** [comment]
I implemented the functionality in Python and now the data is available in javascript. However, at the javascript part there are some steps that needs to be taken to get it up-and-running. It is less straightforward than expected.

**Comment by erdogant** [comment]
It is now possible to change the node and edge colors in the chord chart!
See the [documentation pages ](https://d3blocks.github.io/d3blocks/pages/html/Chord.html) for an example.
Update to the newest version with: `pip install -U d3blocks`

_Thank you @oliver3 for helping in this matter!_

**Comment by erdogant** [comment]
I am closing this issue.
