### ISSUE TITLE
TypeError in version 1.2.10

### ISSUE THREAD

**Issue by dawiseman** [d3blocks/d3blocks#30]
First off, love the work you've done with the `d3blocks` package!

It looks like the most recent merge may've broke something. The error is flagged here:
https://github.com/d3blocks/d3blocks/blob/835dd6452f98715967ceb36d0f11c3b3e2823c78/d3blocks/d3blocks.py#L236

This error occurs in version 1.2.10, but not in 1.2.9
![image](https://user-images.githubusercontent.com/57689370/226386953-8ab6c372-576a-420b-9903-5573294db09e.png)

Thanks again!

(I'm using python 3.7 atm)

**Comment by erdogant** [comment]
Thank you for posting this issue. Interesting because it does not throw an error on my machine. Why would it give a type error? Can you try to change the line into:
`reset_properties=True`

**Comment by dawiseman** [comment]
Gave it a try, even though it looks like you may've found the source
![image](https://user-images.githubusercontent.com/57689370/226435413-876e0a6a-cbae-4251-b034-f29283b25607.png)

**Comment by erdogant** [comment]
I removed the type hinting from the violin plot.
Can you maybe install from the github repo and see whether it still throws an error?

`pip install -U git+https://github.com/d3blocks/d3blocks
`

**Comment by erdogant** [comment]
update to the latest version. Should be fixed now. 

`pip install -U d3blocks
`
