### ISSUE TITLE
The blogs/tutorials are behind a paywall

### ISSUE THREAD

**Issue by nav9** [d3blocks/d3blocks#31]
I was very excited to hear about D3 Blocks, but when I reached the GitHub page and looked for some sample programs, I saw that the links led me back to the articles on Medium.com, and as you can see from the screenshots in this link (https://ibb.co/Z1CdkmP), Medium has blocked access with a restriction of being able to read only 2 articles for free per day unless the User makes a payment for a subscription. This is not how an open source project's knowledge should be available. 
I understand you wrote the articles on Medium because it provides good visibility. However, I request that you copy the same articles onto [GitHub Pages](https://pages.github.com/) or Blogger or WordPress or some other place where the content can be accessed without there being a paywall. At least the links in the readme should lead to those free sources instead of leading to Medium.

**Comment by erdogant** [comment]
Hi @nav9, thank you for your interest and using d3blocks. This library is fully open source and free of use under its license. If you really want to be supportive, you can buy me a coffee or subscribe to medium under [this](https://medium.com/@erdogant/membership)  link. It only cost you 5$ pm and you can read as much as you want! However, If you really want to remove paywalls, go to my [sponsor page](https://d3blocks.github.io/d3blocks/pages/html/Documentation.html#) and surprise me with a huuuuuge number!

**Comment by nav9** [comment]
The better way to answer me would have been to say that I could download the project and go to the `index.html` page in the `docs` [folder](https://github.com/d3blocks/d3blocks/blob/main/docs/index.html) of the downloaded files, and I'd be able to see the examples and explanations there. Nice library. However, I wonder how many people would have reached this GitHub page and not bothered trying this library because of the paywall. I hope you understand how some people evaluate something new.

**Comment by erdogant** [comment]
Ah I see. Well there is tons of examples on the [documentation pages](https://d3blocks.github.io/d3blocks/) indeed. All
these links are also provided in the blogs, docstrings, and readme file and cross referenced.
