### ISSUE TITLE
Tidy tree feature

### ISSUE THREAD

**Issue by mattgra** [d3blocks/d3blocks#33]
Is it currently possible to generate tidy trees similar to this [example](https://observablehq.com/@d3/tree)?
If not - is this feature planned?

**Comment by erdogant** [comment]
Looks great indeed! I first need your help though. Can you can follow the guidelines on "_How to use this chart outside of Observable_" and create a HTML with some data included? With that html file, I can make some of the input variable and integrate it into d3blocks.

**Comment by erdogant** [comment]
Closing this issue!
