### ISSUE TITLE
Issue importing, minmax_distance: list[float] = [50, 100] in d3graph.py, line 879

### ISSUE THREAD

**Issue by hipeilin** [d3blocks/d3blocks#34]
Hi, I want to try out this library today and tried to follow the blog post, I got an error just when trying to import it. The error came from this file `"d3graph.py", line 879, in <module>`
```
    minmax_distance: list[float] = [50, 100],
TypeError: 'type' object is not subscriptable
```
Am I missing something perhaps?

**Comment by erdogant** [comment]
Mm not sure.

Does this work?

```
from d3blocks import D3Blocks

# Initialize
d3 = D3Blocks()

df = d3.import_example(data='energy')

d3.d3graph(df, filepath='d3graph.html', showfig=False)

# Set edge properties
d3.D3graph.set_edge_properties(minmax_distance=[50, 100])
d3.D3graph.set_node_properties(color='cluster')

# Plot
d3.D3graph.show()


```

**Comment by oliver3** [comment]
The type annotation in d3blocks is only valid [from Python 3.9 onwards](https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections) unfortunately. Can you confirm that your Python version is older than that?

**Comment by hipeilin** [comment]
I see! That was indeed the problem, I was using an older version Python. Switched to a newer one (just happen to have 3.10) and it worked immediately! Thanks.
