### ISSUE TITLE
How to change node colors in sankey plots?

### ISSUE THREAD

**Issue by Smilenone** [d3blocks/d3blocks#37]
I would like to generate a sankey plot by using following code:

```
d3 = D3Blocks(chart='Sankey', frame=True)
d3.set_node_properpodties(data)
d3.set_edge_properties(data, color='target', opacity='target')
d3.sankey(data)
```
How to change node colors in sankey plots?

**Comment by erdogant** [comment]
At the moment, the colors can only be changed from source/target. I guess you want to color edges and nodes? That would be a great new functionality indeed.

**Comment by erdogant** [comment]
I added this functionality to the sankey plot!
Update with `pip install -U d3blocks`

An example can be found [here](https://d3blocks.github.io/d3blocks/pages/html/Sankey.html)

**Comment by Smilenone** [comment]
Thank you for your help, but the corresponding edge color does not change with the node?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "d3blocks/d3blocks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 上午6:00
***@***.***&gt;;
抄送:&nbsp;"Qunlun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [d3blocks/d3blocks] How to change node colors in sankey plots? (Issue #37)





 
I added this functionality to the sankey plot!
 Update with pip install -U d3blocks
 
An example can be found here

**Comment by erdogant** [comment]
True. That would be the next step! Feel free to give it a try!

**Comment by erdogant** [comment]
I fixed the edge colors too.
Update and it should work now. See also the documentation pages for examples.
