### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by getmykhan** [d3blocks/d3blocks#39]
Hi, 

Please see the image below, 

![image](https://github.com/d3blocks/d3blocks/assets/15202558/310e28af-3a12-48e2-b2ee-9a30b77b5190)

**Comment by erdogant** [comment]
I can not reproduce the error. Are you using colab?

**Comment by getmykhan** [comment]
@erdogant https://colab.research.google.com/drive/1WlDKdc1-5jlVIZLx11nmJoJhXlXoKIne

Let me know when you get a chance to play with this

**Comment by erdogant** [comment]
Thank you for providing is example! I could reproduce the error and fix it.
Can you check whether it works for you too?

update to the latest version with:
`pip install -U d3blocks
`
