### ISSUE TITLE
Saving graphics as high resolution image

### ISSUE THREAD

**Issue by candidechamp** [d3blocks/d3blocks#42]
Hi, 

First of all thanks for all of the efforts that is going into this great project. 

I was trying to save some graphics (chord diagrams) which I am creating from a jupyter notebook to include them in a publication, hence it would be great to save them in an image format with high resolution. 

Would it be possible to save the diagrams directly into an image format rather than going through an intermediate html file? Right now my only option seems to be taking a screenshot of the picture which doesn't look very nice when rescaling the image. 

Thanks a lot in advance for any advice.

**Comment by erdogant** [comment]
Very valid point. I am going to look into it.

**Comment by erdogant** [comment]
I added the functionality to save each chart using a save button on the HTML.
You can now enable this by `save_button=True`

I also added a [bit of documentation](https://d3blocks.github.io/d3blocks/pages/html/helper_functions.html#saving-charts) regarding the saving functionality.
 
Update to the latest version with `pip install -U d3blocks`

**Comment by candidechamp** [comment]
This is great thanks a lot!
