### ISSUE TITLE
Inclusion of "ethical ads"

### ISSUE THREAD

**Issue by qhga** [d3blocks/d3blocks#44]
Hi, 

thanks again for the time you invested in this project. Today I reviewed the code that was generated when I tried to use this library to create a chord diagram and was surprised to see that there is a script tag which loads some javascript from `https://media.ethicalads.io` and a div that is probably used to link your account to their service.

```
// ...
<div id="chart"></div>

<script async src='https://media.ethicalads.io/media/client/ethicalads.min.js'></script>
<div data-ea-publisher='erdogantgithubio' data-ea-type='text' data-ea-style='stickybox'></div>
// ...
```

Some examples can be found here: [1](https://github.com/d3blocks/d3blocks/blob/e922d6df3c7090f8e98aaabbe24f901701c4d96c/docs/pages/html/Chord.html#L412), [2](https://github.com/d3blocks/d3blocks/blob/e922d6df3c7090f8e98aaabbe24f901701c4d96c/docs/pages/html/Tree.html#L372), [3](https://github.com/d3blocks/d3blocks/blob/e922d6df3c7090f8e98aaabbe24f901701c4d96c/docs/pages/html/Sankey.html#L371), etc.

In my opinion (could be totally wrong) this should either be omitted by default (opt in, not opt out) when generating diagrams or at least be disclosed in the README, not just the docstring/documentation page.
Otherwise, this kinda feels the same as if someone would install a lightweight crypto miner alongside free software without asking me or at least telling me that this would support further development and therefore is mandatory.

**Comment by erdogant** [comment]
I Don’t agree but if dont want to support in this way, you can turn it [off](https://d3blocks.github.io/d3blocks/pages/html/d3blocks.d3blocks.html).

See [here](https://d3blocks.github.io/d3blocks/pages/html/Documentation.html) where you can support in any other way.

**Comment by qhga** [comment]
Yes, I also saw that option and updated the original issue at the same time you answered. I still would suggest that this should be opt in and not opt out. Anyways, thanks for you answer.

**Comment by erdogant** [comment]
Thanks for the feedback.
