### ISSUE TITLE
Sankey font size

### ISSUE THREAD

**Issue by davide-aloi** [d3blocks/d3blocks#45]
Hi there!

First of all, amazing work, I am using your sankey plots a lot and they are very helpful.

I was wondering whether there was a way of increasing the font size of the labels on each rectangle?

Best
Davide

**Comment by erdogant** [comment]
This would be great yes.
I added this variable and created a new release.
Update to the latest version with `pip install -U d3blocks`

```
from d3blocks import D3Blocks
d3 = D3Blocks()

# Sankey
df = d3.import_example(data='energy')
html = d3.sankey(df, fontsize=12)

```

**Comment by davide-aloi** [comment]
Amazing, thanks!

**Comment by davide-aloi** [comment]
Hi @erdogant.

I believe the latest commit broke the function set_node_properties:
Trying to generate a sankey from a table i.e.,

` # Sort the Sankey table by 'source'
sankey_table.sort_values(by='source', inplace=True)

# Create a D3Blocks Sankey chart
d3 = D3Blocks(chart='Sankey', frame=True)
d3.config['figsize'] = [1200, 800]
d3.config['fontsize'] = fontsize

# Node properties
sankey_table['source'] = sankey_table['source'].astype(str)
sankey_table['target'] = sankey_table['target'].astype(str)
sankey_table['weight'] = sankey_table['weight'].astype(str)
d3.set_node_properties(sankey_table)

# Edge properties
d3.set_edge_properties(sankey_table, color='target', opacity='target')`
now returns

dict_labels[label] = {'id': i, 'label': label, 'color': getcolor, 'fontsize': kwargs['node']['fontsize']}     
KeyError: 'node'

**Comment by erdogant** [comment]
It should be fixed now. Can you give it a try?

**Comment by erdogant** [comment]
I fixed the bug! Update to the latest version with `pip install -U d3blocks`
