### ISSUE TITLE
Tooltip in treemap

### ISSUE THREAD

**Issue by jtplaarj** [d3blocks/d3blocks#47]
Hi!

I very much like this project.

I have a question/suggestion. Is it possible to have a tooltip in treemap graphs?

**Comment by erdogant** [comment]
I added this functionality into v1.4.10!
Update to the latest version with pip install -U d3blocks
See an example in the [docs](https://d3blocks.github.io/d3blocks/pages/html/Treemap.html).

If you wish to buy me a [Coffee](https://erdogant.github.io/donate/?currency=USD&amount=5) for this work, it is very appreciated :)

**Comment by jtplaarj** [comment]
Thank you very much.
