### ISSUE TITLE
"color for link " is not aviliable in chord.

### ISSUE THREAD

**Issue by YukunQu** [d3blocks/d3blocks#49]
I provided a list containing ['#000000',....] to the d3.chord, but it resulted in an error. The error occurred in the file ~/Software/anaconda3/lib/python3.8/site-packages/d3blocks/chord/Chord.py at line 342. in get_data_ready_for_d3(df, labels)
    340 X = X + ' "links":['
    341 for _, row in df.iterrows():
--> 342     X = X + '{"source":' + str(row['source_id']) + ',"target":' + str(row['target_id']) + ',"value":' + str(row['weight']) + ',"opacity":' + str(row['opacity']) + ',"color":' + '"' + str(row['color']) + '"' + '},'
    343 X = X[:-1] + ']}'
    345 # Return
    
    
When I set the color in the dataframe, it still didn't work. Do you know the reason and how to fix it?

**Comment by erdogant** [comment]
Does this toy example work for you?

```

# Load d3blocks
from d3blocks import D3Blocks
#
# Initialize
d3 = D3Blocks(chart='Chord', frame=False)
#
# Import example
df = d3.import_example('energy')
#
# Node properties
d3.set_node_properties(df, opacity=0.2, cmap='tab20')
d3.set_edge_properties(df, color='source', opacity='source')
#
# Show the chart
d3.show()
#
# Make some edits to highlight the Nuclear node
# d3.node_properties
d3.node_properties.get('Nuclear')['color']='#ff0000'
d3.node_properties.get('Nuclear')['opacity']=1
# Show the chart
#
d3.show()

# Make edits to highlight the Nuclear Edge
d3.edge_properties.loc[(d3.edge_properties['source'] == 'Nuclear') & (d3.edge_properties['target'] == 'Thermal generation'), 'color'] = '#ff0000'
d3.edge_properties.loc[(d3.edge_properties['source'] == 'Nuclear') & (d3.edge_properties['target'] == 'Thermal generation'), 'opacity'] = 0.8
d3.edge_properties.loc[(d3.edge_properties['source'] == 'Nuclear') & (d3.edge_properties['target'] == 'Thermal generation'), 'weight'] = 1000
#
# Show the chart
d3.show()

```
